import "./global.css";// Importar css
import Link from "next/link";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body>
        <header><h2>Cabecera Principal</h2></header>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/acerca">Acerca</Link>
          <Link href="/contacto">Contacto</Link>
          <Link href="/productos">Productos</Link>
          <Link href="/login">Login</Link>
          <Link href="/registro">Registro</Link>
          <Link href="/password">Recuperar Password</Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
          <main>
            {children}
          </main>
        <footer>Footer Principal</footer>
      </body>
    </html>
  )
}
